version: '3'

services:
    backend:
        container_name: flask
        build: "."
        volumes:
          - .:/usr/src/app
        ports:
          - "5000:5000"
        command: python -m flask run -h 0.0.0.0 -p 5000
        environment:
          FLASK_ENV: development
    